# Generated by Django 4.2.27 on 2026-01-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL for verification'),
        ),
    ]
