# Generated by Django 4.2.27 on 2026-01-29 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-is_featured', '-created_at']},
        ),
    ]
