# Generated by Django 4.2.27 on 2026-02-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='case_study_url',
            field=models.URLField(blank=True, help_text='Link to detailed case study or blog post'),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web_apps', 'Web Apps'), ('backend', 'Backend'), ('ai_agents', 'AI Agents & Agentic Workflow'), ('open_source', 'Open Source'), ('data_engineering', 'Data Engineering')], default='web_apps', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='documentation_url',
            field=models.URLField(blank=True, help_text='Link to project documentation'),
        ),
        migrations.AddField(
            model_name='project',
            name='stars',
            field=models.IntegerField(default=0, help_text='GitHub stars or popularity indicator'),
        ),
    ]
