# Generated by Django 4.2.27 on 2026-02-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_case_study_url_project_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.CharField(blank=True, help_text="Comma-separated category keys (e.g., 'web_apps,backend')", max_length=200),
        ),
    ]
