# Generated by Django 4.2.27 on 2026-02-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_category_project_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='architecture',
            field=models.TextField(blank=True, help_text='Technical architecture, system design, implementation details'),
        ),
        migrations.AddField(
            model_name='project',
            name='challenges',
            field=models.TextField(blank=True, help_text='Problems you encountered and how you solved them'),
        ),
        migrations.AddField(
            model_name='project',
            name='key_features',
            field=models.TextField(blank=True, help_text='Markdown list of key features (use - for bullets)'),
        ),
        migrations.AddField(
            model_name='project',
            name='problem_statement',
            field=models.TextField(blank=True, help_text='What problem does this project solve? Why was it needed?'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, choices=[('personal', 'Personal Project'), ('freelance', 'Freelance/Client Work'), ('company', 'Company Project'), ('open_source', 'Open Source Contribution'), ('hackathon', 'Hackathon'), ('academic', 'Academic/Research')], help_text='Type of project', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='results_impact',
            field=models.TextField(blank=True, help_text='Outcomes, metrics, impact, or achievements'),
        ),
        migrations.AddField(
            model_name='project',
            name='solution_overview',
            field=models.TextField(blank=True, help_text='Your approach and solution. How did you solve it?'),
        ),
        migrations.AddField(
            model_name='project',
            name='team_size',
            field=models.IntegerField(blank=True, help_text='Number of people on the team (leave blank for solo)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='your_role',
            field=models.CharField(blank=True, help_text="Your role in the project (e.g., 'Full-Stack Developer', 'Team Lead')", max_length=200),
        ),
    ]
