# Generated by Django 4.2.27 on 2026-02-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_architecture_project_challenges_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_published',
        ),
        migrations.AddField(
            model_name='project',
            name='show_on_about_page',
            field=models.BooleanField(default=False, help_text='Show this project in the Projects section of the About Me page'),
        ),
    ]
