# Generated by Django 4.2.27 on 2026-01-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='certifications',
            field=models.IntegerField(default=0, help_text='Number of certifications obtained'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='clients_served',
            field=models.IntegerField(default=0, help_text='Number of clients served'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='projects_completed',
            field=models.IntegerField(default=0, help_text='Number of projects completed'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='years_experience',
            field=models.IntegerField(default=0, help_text='Years of professional experience'),
        ),
    ]
