# Generated by Django 4.2.27 on 2026-01-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_certifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='beyond_coding',
            field=models.TextField(blank=True, help_text='Beyond Coding/Interests section'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='currently_learning',
            field=models.TextField(blank=True, help_text='Currently Learning section'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='my_philosophy',
            field=models.TextField(blank=True, help_text='My Philosophy section'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='what_i_do',
            field=models.TextField(blank=True, help_text='What I Do section'),
        ),
    ]
