# Generated by Django 4.2.27 on 2026-01-27 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_beyond_coding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='currently_learning',
        ),
    ]
