# Generated by Django 4.2.27 on 2026-01-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_sitesettings_currently_learning'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='current_projects',
            field=models.TextField(blank=True, help_text='Currently - Current Projects subsection'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='currently_learning',
            field=models.TextField(blank=True, help_text='Currently - Learning subsection'),
        ),
    ]
