# Generated by Django 4.2.27 on 2026-01-27 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_current_projects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='beyond_coding',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='my_philosophy',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='what_i_do',
        ),
    ]
