# Generated by Django 4.2.27 on 2026-01-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_sitesettings_beyond_coding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='home_bio',
            field=models.TextField(blank=True, help_text='Short bio for home page hero section'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='bio',
            field=models.TextField(help_text='Detailed bio for about page'),
        ),
    ]
