# Generated by Django 4.2.27 on 2026-01-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesettings_home_bio_alter_sitesettings_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'subcategory', 'order', 'name'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='proficiency',
        ),
        migrations.AddField(
            model_name='skill',
            name='details',
            field=models.CharField(blank=True, help_text='Optional details (e.g., Optimization, Schema Design)', max_length=200),
        ),
        migrations.AddField(
            model_name='skill',
            name='subcategory',
            field=models.CharField(default='Other', help_text='Subcategory (e.g., Languages, Web Frameworks)', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('compute', 'Compute & Application Logic'), ('data', 'Data Strategy & Persistence'), ('platform', 'Platform Engineering (Infrastructure)'), ('devops', 'DevOps & Delivery Automation'), ('observability', 'Observability & Reliability (SRE)'), ('architecture', 'System Architecture & Networking')], help_text='Main category', max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text='Devicon class (e.g., devicon-python-plain colored)', max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(help_text='Technology name (e.g., PostgreSQL, Docker)', max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order within subcategory'),
        ),
    ]
