# Generated by Django 4.2.27 on 2026-01-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_skill_options_remove_skill_proficiency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='my_story',
            field=models.TextField(blank=True, help_text='My Story section content for about page'),
        ),
    ]
