# Generated by Django 4.2.27 on 2026-01-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_skill_options_sitesettings_my_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show on landing page'),
        ),
    ]
