# Generated by Django 4.2.27 on 2026-01-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('excerpt', models.TextField(help_text='Short description for previews', max_length=300)),
                ('content', models.TextField(help_text='Full blog post content (supports Markdown)')),
                ('cover_image', models.ImageField(blank=True, help_text='Featured image', null=True, upload_to='blog/')),
                ('author', models.CharField(default='Pawan Kumar', max_length=100)),
                ('published_date', models.DateTimeField(help_text='When to publish this post')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False, help_text='Make post visible')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('read_time', models.IntegerField(default=5, help_text='Estimated reading time in minutes')),
                ('views', models.IntegerField(default=0, help_text='Number of views')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_date'],
            },
        ),
    ]
