# Generated by Django 4.2.27 on 2026-01-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='external_url',
            field=models.URLField(blank=True, help_text='Link to externally published blog (e.g., Medium, Dev.to)'),
        ),
    ]
