# Generated by Django 4.2.27 on 2026-01-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order (lower first)'),
        ),
    ]
