# Generated by Django 4.2.27 on 2026-01-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='platform_name',
            field=models.CharField(blank=True, help_text='Platform name for external link (e.g., Medium, Dev.to)', max_length=50),
        ),
    ]
