# Generated by Django 4.2.27 on 2026-01-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(max_length=200)),
                ('organization_logo', models.ImageField(blank=True, null=True, upload_to='certifications/logos/')),
                ('credential_id', models.CharField(blank=True, max_length=200)),
                ('credential_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('date_obtained', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date_obtained', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.CharField(max_length=200)),
                ('institution_logo', models.ImageField(blank=True, null=True, upload_to='education/logos/')),
                ('institution_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('degree', models.CharField(choices=[('phd', 'Ph.D.'), ('masters', "Master's Degree"), ('bachelors', "Bachelor's Degree"), ('associate', 'Associate Degree'), ('diploma', 'Diploma'), ('certificate', 'Certificate'), ('other', 'Other')], max_length=20)),
                ('field_of_study', models.CharField(max_length=200)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['-start_date', 'order'],
            },
        ),
    ]
