# Generated by Django 4.2.27 on 2026-01-29 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['order', '-date_obtained']},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['order', '-start_date'], 'verbose_name_plural': 'Education'},
        ),
    ]
