# Generated by Django 4.2.27 on 2026-01-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of downloader')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device information')),
                ('referrer', models.URLField(blank=True, help_text='Page they came from', max_length=500)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('download_source', models.CharField(choices=[('modal', 'Resume Modal'), ('direct', 'Direct Link'), ('navbar', 'Navbar')], default='modal', help_text='Where the download was initiated', max_length=50)),
            ],
            options={
                'verbose_name': 'Resume Download',
                'verbose_name_plural': 'Resume Downloads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='analytics_r_created_820267_idx'), models.Index(fields=['ip_address'], name='analytics_r_ip_addr_9ce974_idx')],
            },
        ),
    ]
